<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>desktop_app</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="MouseKeyHook" Version="5.7.1" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.8" />
    <PackageReference Include="WPF-UI" Version="4.3.0" />
    <!-- Thêm gói hỗ trợ Render Markdown tương thích Dark Theme -->
    <PackageReference Include="WPF-UI.Markdown" Version="3.0.5.4" />
  </ItemGroup>

</Project>